apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-index-g
data: 
  index.html: | 
    <html> 
      <head><title> The Green page</title></head>
      <body style="background-color: green">
        <h1> Welcome</h1>
        <br>
        <h2> Hi! This is green page</h2>
      </body>
    </html>  
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment-g
spec:
  selector:
    matchLabels:
      app: nginx-g
  replicas: 1
  template:
    metadata:
      labels:
        app: nginx-g
    spec:
      containers:
      - name: nginx-g
        image: nginx
        ports:
        - containerPort: 80
        volumeMounts:
            - name: nginx-index-file
              mountPath: /usr/share/nginx/html/
      volumes: 
      - name: nginx-index-file
        configMap:
          name: nginx-index-g
